config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :schools do
    resources :classrooms
  end

  resources :students

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :school
end

app/models/school.rb
class School < ApplicationRecord
  has_many :classrooms

  validates :name, :address, :telephone, presence: true

  enum kind: %i(kinder elementary high), _suffix: :school
  enum regimen: %i(city state federal private), _suffix: :school
end

app/models/student.rb
class Student < ApplicationRecord
  enum sex: %i(male female other)

  def age
    return Time.now.year - birthday.year
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :get_school
  before_action :set_classroom, only: [:show, :edit, :update, :delete]

  def index
    @classrooms = @school.classrooms
  end

  def show
  end

  def create
    @classroom = @school.classrooms.build classroom_params

    if @classroom.save then
      redirect_to @school
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @classroom = @school.classrooms.build
  end

  def edit
  end

  def update
    if @clasroom.update classroom_params then
      redirect_to @school
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def delete
    @classroom = Classroom.find params[:id]
    @classroom.delete

    redirect_to schools_url
  end

  private

  def get_school
    @school = School.find params[:school_id]
  end

  def set_classroom
    @classroom = @school.classrooms.find params[:id]
  end

  def classroom_params
    params.require(:classroom).permit(:name, :year, :capacity, :school_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  # GET /
  def index
    @schools = School.all
  end

  # GET /:id/
  def show
    @school = School.find params[:id]
  end

  # GET /new/
  def new
    @school = School.new
  end

  # POST /
  def create
    @school = School.new school_params

    if @school.save then
      redirect_to @school
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET /:id/edit
  def edit
    @school = School.find params[:id]
  end

  # PUT,PATCH /:id
  def update
    @school = School.find params[:id]

    if @school.update school_params
      redirect_to @school
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /:id
  def destroy
    @school = School.find params[:id]
    @school.delete

    redirect_to schools_url
  end

  #
  #
  private

  def school_params
    params.require(:school).permit(:name, :address, :telephone, :kind, :regimen)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def enum_to_translated_select (hash, preffix:)
    preffix = preffix.join(".") if preffix.kind_of? Array
    preffix << "." if not preffix.end_with? "."

    return hash
      .map {
        |k, v| [I18n.t(preffix + k.to_s, default: k.to_s), k]
      }.to_h
  end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/classrooms/new.html.erb
<%= form_with model: [@school, @classroom] do |form| %>
    <div>
        <%= form.label :name, "Nome" %>
        <%= form.text_field :name %>

        <%= render "components/errors", errors: @classroom.errors.full_messages_for(:name) %>
    </div>

    <div>
        <%= form.label :year, "Ano" %>
        <%= form.number_field :year %>

        <%= render "components/errors", errors: @classroom.errors.full_messages_for(:year) %>
    </div>

    <div>
        <%= form.label :capacity, "Capacidade" %>
        <%= form.number_field :capacity %>

        <%= render "components/errors", errors: @classroom.errors.full_messages_for(:capacity) %>
    </div>
    
    <%= form.submit "Criar turma" %>
<% end %>

app/views/home/index.html.erb
<h1>Bem-vindo(a) ao Sistema de Gerência de Matrículas</h1>

<ul>
    <li>Gerencie escolas e turmas</li>
    <li>Cadastre alunos</li>
    <li>Gere relatórios</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SistemaDeMatriculas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "content", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= yield :head %>
  </head>

  <body>
    <main>
      <%= render "/components/sidebar" %>
      
      <div class="content">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/schools/_form.html.erb
<%= content_for :head do %>
    <%= stylesheet_link_tag "partials/errors" %>
<% end %>

<%= form_with model: school, class: "form" do |form| %>
    <div>
        <%= form.label :name, "Nome" %>
        <%= form.text_field :name %>

        <%= render "components/errors", errors: school.errors.full_messages_for(:name) %>
    </div>

    <div>
        <%= form.label :address, "Endereço" %>
        <%= form.text_field :address %>

        <%= render "components/errors", errors: school.errors.full_messages_for(:address) %>
    </div>

    <div>
        <%= form.label :telephone, "Telefone" %>
        <%= form.text_field :telephone %>

        <%= render "components/errors", errors: school.errors.full_messages_for(:telephone) %>
    </div>
    
    <div>
        <%= form.label "Tipo" %>
        <%= form.select :kind, enum_to_translated_select(School.kinds, preffix: "enum.kind") %>

        <%= render "components/errors", errors: school.errors.full_messages_for(:kind) %>
    </div>

    <div>
        <%= form.label "Regime" %>
        <%= form.select :regimen, enum_to_translated_select(School.regimen, preffix: "enum.regimen") %>
        <%= render "components/errors", errors: school.errors.full_messages_for(:regimen) %>
    </div>

    <%= form.submit submit_text, class: "button active" %>
<% end %>

app/views/schools/_inline_school.html.erb
<%= link_to school, class: "inline-school" do %>
    <section class="icon">
        <%= image_tag "school.svg", draggable: false %>
    </section>
    <div class="separator"></div>
    <section class="data">
        <p class="name"><%= school.name %></p>
        <p class="address"><%= school.address %></p>
        <p class="contact"><%= school.telephone %></p>
    </section>
<% end %>

app/views/schools/_school.html.erb
<div class="school">
    <h1><%= school.name %></h1>
    <hr>
    <br>

    <p class="name"><%= school.name %></p>
    <p class="address"><%= school.address %></p>
    <p class="contact"><%= school.telephone %></p>

    <br>

    <table class="table">
        <thead>
            <th>#</th>
            <th>Nome</th>
            <th>Ano</th>
            <th>Capacidade</th>
        </thead>
        <tbody>
            <% if school.classrooms.empty? then %>
                <p>Sem turmas cadastradas.</p>
            <% else %>
                <% school.classrooms.each do |classroom| %>
                    <tr>
                        <td><%= classroom.id %></td>
                        <td><%= classroom.name %></td>
                        <td><%= classroom.year %></td>
                        <td><%= classroom.capacity %></td>
                    </tr>
                <% end %>
            <% end %>
            <tr>
                <%= link_to "Adicionar turma", new_school_classroom_url(school) %>
            </tr>
        </tbody>
    </table>

    <br>

    <footer class="actions">
        <%= link_to "Voltar", schools_url, class: "button active" %>
        <%= link_to "Editar", edit_school_url(school), class: "button normal" %>
        <%= link_to "Excluir", school, class: "button delete", data: { "turbo-method": "delete" } %>
    </footer>
</div>

app/views/schools/edit.html.erb
<%= render "form", school: @school, submit_text: "Editar" %>

app/views/schools/index.html.erb
<%= content_for :head do %>
    <%= stylesheet_link_tag "partials/school" %>
<% end %>

<h1>Escolas cadastradas</h1>
<hr>

<ul class="schools">
    <% if @schools.empty? then %>
        <p>Nenhuma escola cadastrada.</p>
    <% else %>
        <% @schools.each do |school| %>
            <%= render "inline_school", school: school %>
        <% end %>
    <% end %>
</ul>

<%= link_to "Cadastre", new_school_url, class: "button active" %>

app/views/schools/new.html.erb
<h1>Cadastre uma escola</h1>
<hr>

<%= render "form", school: @school, submit_text: "Cadastrar" %>

app/views/schools/show.html.erb
<%= render @school %>

app/views/students/_student.html.erb
<div>
    <p>
        <%= student.cpf %>
    </p>
    <p>
        <%= student.name %>
    </p>

    <p>
    <% case student.age %>    
    <% when 0 %>
        0
    <% when 1 %>
        1
    <% when 2 %>
        2
    <% end %>
    </p>
</div>

app/views/students/index.html.erb
<%= render @students %>